"""Central configuration, loaded from environment variables.

Everything the app needs is declared here so a missing value fails loudly at
startup instead of halfway through a request.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict

# Single source of truth for the embedding width. pgvector fixes the column
# dimension at DDL time, so every provider is normalised to this size:
#   - Gemini  text-embedding-004      -> natively 768
#   - OpenAI  text-embedding-3-small  -> requested at 768 via `dimensions`
#   - offline deterministic fallback  -> hashed into 768
EMBED_DIM = 768


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # --- Runtime -------------------------------------------------------------
    environment: Literal["local", "dev", "prod"] = "local"
    log_level: str = "INFO"

    # --- Database ------------------------------------------------------------
    database_url: str = "postgresql://postgres:postgres@localhost:5432/sentellent"
    db_pool_min: int = 1
    db_pool_max: int = 8

    # --- Auth ----------------------------------------------------------------
    # Signs the session JWT. Generated by Terraform in AWS; any string locally.
    session_secret: str = "dev-only-insecure-secret-change-me"
    session_ttl_hours: int = 24 * 7

    google_client_id: str = ""
    google_client_secret: str = ""
    # Must exactly match an "Authorised redirect URI" in Google Cloud Console.
    oauth_redirect_uri: str = "http://localhost:8000/api/auth/google/callback"
    # Where the user lands after login completes.
    frontend_base_url: str = "http://localhost:3000"

    # When Google credentials are absent (local dev, CI) allow a stub login so
    # the whole app is still exercisable. Force-disabled in prod below.
    allow_dev_login: bool = True

    # --- LLM provider --------------------------------------------------------
    llm_provider: Literal["gemini", "openai", "anthropic", "echo"] = "echo"
    llm_model: str = ""  # blank -> provider default
    llm_temperature: float = 0.1
    llm_max_tokens: int = 1600

    embedding_provider: Literal["gemini", "openai", "hash"] = "hash"
    embedding_model: str = ""  # blank -> provider default

    google_api_key: str = ""
    openai_api_key: str = ""
    anthropic_api_key: str = ""

    # --- Ingestion -----------------------------------------------------------
    ingest_news_per_ticker: int = 25
    ingest_http_timeout: float = 20.0
    ingest_user_agent: str = (
        "SentellentEquityAnalyst/1.0 (hiring-challenge; contact via GitHub repo)"
    )
    # Cosine distance below which two articles are treated as the same story.
    near_duplicate_threshold: float = 0.06
    # Half-life in days for the rolling per-stock sentiment decay.
    sentiment_half_life_days: float = 7.0

    # --- Retrieval -----------------------------------------------------------
    retrieval_top_k: int = 8
    retrieval_candidate_k: int = 40
    # Weight of keyword (BM25-ish) score when fused with vector similarity.
    hybrid_keyword_weight: float = 0.35

    @property
    def is_prod(self) -> bool:
        return self.environment == "prod"

    @property
    def dev_login_enabled(self) -> bool:
        """Never expose the passwordless dev login in a deployed environment."""
        return self.allow_dev_login and not self.is_prod

    @property
    def google_oauth_configured(self) -> bool:
        return bool(self.google_client_id and self.google_client_secret)


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
